# Generated by Django 5.1.6 on 2025-02-23 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_profile_id_alter_profile_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('cityname', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('location_id', models.CharField(max_length=255)),
                ('city_image', models.TextField()),
                ('is_active', models.IntegerField(default=1)),
                ('enable_car_delivery_is_active', models.IntegerField(default=0)),
                ('select_default_pricing_model', models.CharField(max_length=255)),
                ('select_default_pricing_model_is_active', models.IntegerField(default=0)),
                ('per_km_model_is_active', models.IntegerField(default=0)),
                ('packaging_type', models.CharField(max_length=255)),
                ('weekend_start_day', models.CharField(max_length=50)),
                ('weekend_start_time', models.TimeField()),
                ('weekend_end_day', models.CharField(max_length=50)),
                ('weekend_end_time', models.TimeField()),
                ('operational_hours_start_time', models.TimeField()),
                ('operational_hours_end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CityKmModel',
            fields=[
                ('city_model_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=255)),
                ('plan_provider', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('default_is_active', models.IntegerField(default=0)),
                ('enable_is_active', models.IntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.city')),
            ],
        ),
    ]
