# Generated by Django 5.1.6 on 2025-02-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_city_citykmmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hubs',
            fields=[
                ('hub_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_id', models.IntegerField()),
                ('city_name', models.CharField(max_length=100)),
                ('hub_name', models.CharField(max_length=100)),
                ('hub_type', models.CharField(max_length=50)),
                ('is_active', models.IntegerField(default=1)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
