# Generated by Django 5.1.6 on 2025-02-24 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_hubs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_model_id', models.AutoField(primary_key=True, serialize=False)),
                ('feet_type', models.CharField(max_length=100)),
                ('enter_model_no', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('tank_capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoty', models.CharField(max_length=100)),
                ('seater', models.IntegerField()),
                ('transmission', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(max_length=50)),
                ('milage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('luggage_carrier', models.CharField(max_length=100)),
                ('varient', models.CharField(max_length=100)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_charage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('car_image', models.CharField(max_length=200)),
                ('is_active', models.IntegerField(default=1)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeetCity',
            fields=[
                ('feet_city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_id', models.IntegerField()),
                ('city_name', models.CharField(max_length=100)),
                ('car_model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.car')),
            ],
        ),
    ]
