# Generated by Django 5.1.6 on 2025-02-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_car_feetcity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='enter_model_no',
            new_name='enter_model_name',
        ),
    ]
