# Generated by Django 5.1.6 on 2025-03-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_car_car_image_alter_car_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('provider_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=255)),
                ('supplier_type', models.CharField(max_length=255)),
                ('agreement_id', models.CharField(max_length=255, unique=True)),
                ('agreement_path', models.TextField()),
                ('valid_till_date', models.DateField()),
                ('provider_address', models.TextField()),
                ('provider_city', models.CharField(max_length=255)),
                ('provider_state', models.CharField(max_length=255)),
                ('provider_country', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_mobile', models.CharField(max_length=15)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('contact_designation', models.CharField(max_length=255)),
            ],
        ),
    ]
