# Generated by Django 5.1.6 on 2025-03-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='agreement_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='contact_designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
