# Generated by Django 5.1.6 on 2025-03-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_provider_agreement_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
    ]
