# Generated by Django 5.1.6 on 2025-03-07 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_provider_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('feet_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=255)),
                ('city_id', models.IntegerField()),
                ('car_model_id', models.IntegerField()),
                ('car_model_name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=50)),
                ('provider_type', models.CharField(max_length=255)),
                ('provider_id', models.IntegerField()),
                ('provider_name', models.CharField(max_length=255)),
                ('hub_id', models.IntegerField()),
                ('hub_name', models.CharField(max_length=255)),
                ('registration_no', models.CharField(max_length=50, unique=True)),
                ('chassis_number', models.CharField(max_length=255)),
                ('engine_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FleetDocument',
            fields=[
                ('feet_document_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_document_type', models.CharField(max_length=255)),
                ('upload_document_text', models.TextField()),
                ('document_number', models.CharField(max_length=100, unique=True)),
                ('valid_till_date', models.DateField()),
                ('feet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='myapp.fleet')),
            ],
        ),
    ]
