# Generated by Django 5.1.6 on 2025-03-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_city_packaging_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citykmmodel',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='citykmmodel',
            name='package_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='citykmmodel',
            name='plan_provider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
