# Generated by Django 5.1.6 on 2025-03-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_citykmmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubs',
            name='hub_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
