# Generated by Django 5.1.6 on 2025-03-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_hubs_hub_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='varient',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
